# Generated by Django 5.1.6 on 2025-02-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255, unique=True)),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(default='usd', max_length=10)),
                ('place', models.CharField(default='Cabo Verde', max_length=255)),
                ('time', models.CharField(default='1 hour', max_length=255)),
                ('service', models.CharField(default='Tour', max_length=255)),
                ('distance', models.CharField(default='10 km', max_length=255)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
