# Generated by Django 5.1.6 on 2025-02-15 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='distance',
            field=models.CharField(default='10 km', max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='place',
            field=models.CharField(default='Cabo Verde', max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='service',
            field=models.CharField(default='Tour', max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='time',
            field=models.CharField(default='1 hour', max_length=255),
        ),
    ]
